version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  chromadb:
    image: chromadb/chroma:0.6.3
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8081:8000
    networks:
      - my_network
    depends_on:
      - db
    restart: always
    

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
