import os

EMBED_MODEL_NAME=os.getenv('EMBED_MODEL_NAME')
PREFIX_DIR_MODEL=os.getenv('PREFIX_DIR_MODEL', 'model')
TEXT_GENERATION_MODEL = os.getenv('TEXT_GENERATION_MODEL', 'gpt2')

EMBED_MODEL_PATH = f"{PREFIX_DIR_MODEL}/{EMBED_MODEL_NAME}"

DOCUMENT_PATH = os.getenv('DOCUMENT_PATH', 'storage/documents/')
