"""create_collections_table

Revision ID: 6c0ae0d0b44d
Revises: 0514a6b7892f
Create Date: 2025-04-30 19:02:23.905343

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c0ae0d0b44d'
down_revision: Union[str, None] = '0514a6b7892f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'collections',
        sa.Column('id', sa.UUID, nullable=False, default=sa.text('uuid_generate_v4()')),
        sa.Column('collection_name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),

        # Timestamps
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('collection_name')

    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###
