"""create files table

Revision ID: 0514a6b7892f
Revises: c7451858a8fd
Create Date: 2025-03-29 03:47:52.285887

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0514a6b7892f'
down_revision: Union[str, None] = 'c7451858a8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'files',
        sa.Column('id', sa.UUID, nullable=False, default=sa.text('uuid_generate_v4()')),
        sa.Column('file_name', sa.String(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('file_type', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('metadatas', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),

        # Status of the file ['pending', 'processing', 'completed', 'failed', 'deleted', 'archived']
        sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'deleted', 'archived'
                                    , name='file_status_enum'),
                  nullable=False,
                  server_default='pending',
                  ),
        # Time processing started
        sa.Column('processing_started_at', sa.DateTime(), nullable=True),
        # Time processing ended
        sa.Column('processing_ended_at', sa.DateTime(), nullable=True),

        sa.Column('collection_id', sa.UUID, nullable=False),
        # Foreign key to collections table
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
